import type { Metadata } from "next";
import { lusitana } from "@/app/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${lusitana.className} antialiased bg-slate-950 text-gray-50`}
      >
        {children}
      </body>
    </html>
  );
}
